import { DeliberationResult } from './types.js';

export class ADRGenerator {
  /**
   * Generates a standard Markdown Architectural Decision Record (MADR v3.0 format)
   */
  static generate(result: DeliberationResult, adrNumber = 1): string {
    const bp = result.blueprint;
    const win = bp.winningArchitecture;
    const dateStr = new Date().toISOString().split('T')[0];
    const adrId = String(adrNumber).padStart(4, '0');

    let adr = `# ADR-${adrId}: ${bp.title}\n\n`;
    adr += `* **Status:** Accepted  \n`;
    adr += `* **Deciders:** Adversarial Deliberation Council (${result.councilDebates?.map((d) => d.personaName).join(', ') || 'Core Council'})  \n`;
    adr += `* **Date:** ${dateStr}  \n`;
    adr += `* **Technical Story:** ${result.goal}  \n\n`;

    adr += `## Context and Problem Statement\n\n`;
    adr += `${bp.executiveSummary}\n\n`;
    if (result.context) {
      adr += `### Background Context\n${result.context}\n\n`;
    }

    adr += `## Decision Drivers\n\n`;
    for (const score of win.scores) {
      adr += `* **${score.criterion.toUpperCase()} (Score: ${score.score}/10):** ${score.rationale}\n`;
    }
    adr += `\n`;

    adr += `## Considered Options\n\n`;
    adr += `1. **${win.title}** (Chosen Architecture — Paradigm: \`${win.paradigm}\`)\n`;
    for (const alt of bp.rejectedAlternatives) {
      adr += `2. **${alt.title}** (Rejected)\n`;
    }
    adr += `\n`;

    adr += `## Decision Outcome\n\n`;
    adr += `Chosen option: **${win.title}**, because ${win.tradeOffSummary}\n\n`;

    adr += `### Positive Consequences\n\n`;
    for (const score of win.scores.filter((s) => s.score >= 8.5)) {
      adr += `* Excellent ${score.criterion}: ${score.rationale}\n`;
    }
    adr += `\n`;

    adr += `### Negative Consequences & Mitigations\n\n`;
    for (const fm of bp.failureModesAndMitigations) {
      adr += `* **Risk:** ${fm.failureMode} ➔ **Mitigation:** ${fm.mitigation}\n`;
    }
    adr += `\n`;

    adr += `## Core Invariants & Compliance Rules\n\n`;
    bp.coreInvariants.forEach((inv, idx) => {
      adr += `${idx + 1}. **${inv}**\n`;
    });
    adr += `\n`;

    if (bp.codeSkeleton) {
      adr += `## Architectural Contract Scaffold\n\n`;
      adr += `\`\`\`typescript\n${bp.codeSkeleton}\n\`\`\`\n\n`;
    }

    adr += `## Implementation Steps\n\n`;
    bp.implementationSteps.forEach((step) => {
      adr += `* ${step}\n`;
    });
    adr += `\n`;

    adr += `---\n*Generated by [Deliberate](https://github.com/shanmukhaditya/deliberate) on ${dateStr}*\n`;
    return adr;
  }
}
